github.com:
    users:
        pitt0:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: pitt0
